// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuCtI6dCe6EHO2XF9tctKGEe7j3ykcgH4',
    appId: '1:412804702119:web:b8c513ef47ab15d9a5e082',
    messagingSenderId: '412804702119',
    projectId: 'flutter-auth-e0486',
    authDomain: 'flutter-auth-e0486.firebaseapp.com',
    storageBucket: 'flutter-auth-e0486.appspot.com',
    measurementId: 'G-5S87DG2GCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIxQxBy_rmcNkcdnhBjKQhOypnEzBcU5k',
    appId: '1:412804702119:android:6fe1c825e663a14fa5e082',
    messagingSenderId: '412804702119',
    projectId: 'flutter-auth-e0486',
    storageBucket: 'flutter-auth-e0486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAkgDW2tmeiggHii5BaMz9XoyX6OWreJk',
    appId: '1:412804702119:ios:bc2161089f2ed99fa5e082',
    messagingSenderId: '412804702119',
    projectId: 'flutter-auth-e0486',
    storageBucket: 'flutter-auth-e0486.appspot.com',
    iosBundleId: 'com.example.mohiuddin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAkgDW2tmeiggHii5BaMz9XoyX6OWreJk',
    appId: '1:412804702119:ios:a67c2e06176cf6d1a5e082',
    messagingSenderId: '412804702119',
    projectId: 'flutter-auth-e0486',
    storageBucket: 'flutter-auth-e0486.appspot.com',
    iosBundleId: 'com.example.example.RunnerTests',
  );
}
