// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslX21JB909mQcYnIf55hIPJ3e-m-cJrY',
    appId: '1:977577507743:web:e89e37d8a3188e093e9baa',
    messagingSenderId: '977577507743',
    projectId: 'flutter-app-391817',
    authDomain: 'flutter-app-391817.firebaseapp.com',
    databaseURL: 'https://flutter-app-391817-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-391817.appspot.com',
    measurementId: 'G-7XTR6DFWT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgvarFLuqAYE9By4KeW-No0VKtIQH09J4',
    appId: '1:977577507743:android:8d3d3aa13db90aec3e9baa',
    messagingSenderId: '977577507743',
    projectId: 'flutter-app-391817',
    databaseURL: 'https://flutter-app-391817-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-391817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO8YKNo32mfRa3JV6-U3L-TfDu1KPxan4',
    appId: '1:977577507743:ios:5d4ec12638c284183e9baa',
    messagingSenderId: '977577507743',
    projectId: 'flutter-app-391817',
    databaseURL: 'https://flutter-app-391817-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-391817.appspot.com',
    androidClientId: '977577507743-50cg37c4qkdlld5obv02h1htums57jiq.apps.googleusercontent.com',
    iosClientId: '977577507743-61er1r6j5ivur2jrnfe31bvpcqoe7f1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO8YKNo32mfRa3JV6-U3L-TfDu1KPxan4',
    appId: '1:977577507743:ios:5d4ec12638c284183e9baa',
    messagingSenderId: '977577507743',
    projectId: 'flutter-app-391817',
    databaseURL: 'https://flutter-app-391817-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-391817.appspot.com',
    androidClientId: '977577507743-50cg37c4qkdlld5obv02h1htums57jiq.apps.googleusercontent.com',
    iosClientId: '977577507743-61er1r6j5ivur2jrnfe31bvpcqoe7f1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDslX21JB909mQcYnIf55hIPJ3e-m-cJrY',
    appId: '1:977577507743:web:d00356ada06c71f73e9baa',
    messagingSenderId: '977577507743',
    projectId: 'flutter-app-391817',
    authDomain: 'flutter-app-391817.firebaseapp.com',
    databaseURL: 'https://flutter-app-391817-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-391817.appspot.com',
    measurementId: 'G-HX2S5FSE42',
  );
}
